id: P008119
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG23569
  title: མྱོང་གྲུབ་མན་ངག་ཁ་འཐོར་ཕྱོགས་གཅིག་ཏུ་བཀོད་པ།
  author: ''
  volumes:
    fcb09470a3a7494d951e7e4b3fb5822b:
      image_group_id: I1KG23625
      title: Volume 1 of myong grub man ngag kha 'thor phyogs gcig tu bkod pa/
      volume_number: 1
      total_pages: 490
      base_file: v001.txt
