id: P008119
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG23569
  title: མྱོང་གྲུབ་མན་ངག་ཁ་འཐོར་ཕྱོགས་གཅིག་ཏུ་བཀོད་པ།
  author: ''
  volumes:
    fc77842cbc1a427d8d2785e9b2cb333a:
      image_group_id: I1KG23625
      title: ''
      volume_number: 1
      total_pages: 490
ebook_metadata:
  title: མྱོང་གྲུབ་མན་ངག་ཁ་འཐོར་ཕྱོགས་གཅིག་ཏུ་བཀོད་པ།
  author: ''
  sku: P008119
  cover: cover.jpg
  layers:
  - pagination
